SET DEFINE OFF;

-- ================================================================
-- IMTRA: Insert sample data (7 rows per table) - Rwandan names
-- File: insert_sample_data.sql
-- Created: 2025-12-07
-- ================================================================

PROMPT Inserting sample data...

-- ---------------------------
-- 1) USERS (7)
-- ---------------------------
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('mukamana', 'Mukamana Jean', 'LAB_TECH', 'mukamana@example.rw', '+250788000001');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('nsabimana', 'Nsabimana Alice', 'LAB_TECH', 'alice.nsabimana@example.rw', '+250788000002');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('kagabo', 'Kagabo Emile', 'PHYSICIAN', 'emile.kagabo@example.rw', '+250788000003');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('mutesi', 'Mutesi Claudine', 'PHYSICIAN', 'claudine.mutesi@example.rw', '+250788000004');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('ingabire', 'Ingabire Samuel', 'ADMIN', 'samuel.ingabire@example.rw', '+250788000005');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('ndizeye', 'Ndizeye Marie', 'PHYSICIAN', 'marie.ndizeye@example.rw', '+250788000006');
INSERT INTO USERS (USERNAME, FULL_NAME, ROLE, EMAIL, PHONE) VALUES ('iradukunda', 'Iradukunda Olivier', 'LAB_TECH', 'olivier.iradukunda@example.rw', '+250788000007');

-- ---------------------------
-- 2) PATIENTS (7)
-- ---------------------------
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0001','Jean','Hakizimana', DATE '1985-03-10', 'M', '+250788100001', 'Kigali, Gasabo');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0002','Alice','Uwera', DATE '1992-07-21', 'F', '+250788100002', 'Kigali, Kicukiro');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0003','Emmanuel','Bizimana', DATE '1975-12-05', 'M', '+250788100003', 'Huye');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0004','Claudine','Mugabo', DATE '2000-01-15', 'F', '+250788100004', 'Ruhengeri');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0005','Samuel','Niyonzima', DATE '1968-09-30', 'M', '+250788100005', 'Nyamata');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0006','Marie','Uwase', DATE '1988-05-02', 'F', '+250788100006', 'Rubavu');
INSERT INTO PATIENTS (MRN, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS) VALUES ('MRN0007','Olivier','Habimana', DATE '1999-11-11', 'M', '+250788100007', 'Gisenyi');

-- ---------------------------
-- 3) PHYSICIANS (7) - link some to USERS
-- ---------------------------
INSERT INTO PHYSICIANS (USER_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'kagabo'), 'Emile', 'Kagabo', 'Internal Medicine', 'emile.kagabo@hospital.rw', '+250782000101');
INSERT INTO PHYSICIANS (USER_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'mutesi'), 'Claudine', 'Mutesi', 'Pediatrics', 'claudine.mutesi@hospital.rw', '+250782000102');
INSERT INTO PHYSICIANS (USER_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'ndizeye'), 'Marie', 'Ndizeye', 'Cardiology', 'marie.ndizeye@hospital.rw', '+250782000103');
INSERT INTO PHYSICIANS (FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ('Thomas','Rurangwa','Emergency','thomas.rurangwa@hospital.rw','+250782000104');
INSERT INTO PHYSICIANS (FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ('Beatrice','Umutesi','Oncology','beatrice.umutesi@hospital.rw','+250782000105');
INSERT INTO PHYSICIANS (FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ('Alice','Nyiramana','General Surgery','alice.nyiramana@hospital.rw','+250782000106');
INSERT INTO PHYSICIANS (FIRST_NAME, LAST_NAME, DEPARTMENT, EMAIL, PHONE) VALUES ('Jean','Nshimiyimana','Nephrology','jean.nshimiyimana@hospital.rw','+250782000107');

-- ---------------------------
-- 4) TEST_TYPES (7)
-- ---------------------------
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('HB','Hemoglobin', 'g/dL', 12.0, 17.5, 6.0, 25.0, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('WBC','White Blood Cells', '10^9/L', 4.0, 11.0, 1.0, 50.0, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('GLU','Glucose (Fasting)', 'mmol/L', 3.9, 5.6, 2.0, 30.0, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('CR','Creatinine', 'umol/L', 60, 110, 20, 1000, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('TRO','Troponin I', 'ng/mL', 0.0, 0.04, 1.0, 100.0, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('ALT','Alanine Transaminase', 'U/L', 7, 56, 200, 5000, 'Blood');
INSERT INTO TEST_TYPES (CODE, NAME, UNIT, NORMAL_LOW, NORMAL_HIGH, CRITICAL_LOW, CRITICAL_HIGH, SAMPLE_TYPE) VALUES ('AST','Aspartate Transaminase', 'U/L', 10, 40, 200, 5000, 'Blood');

-- ---------------------------
-- 5) ORDERS (7) - each linking a patient to a physician
-- ---------------------------
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0001'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Kagabo'), TO_TIMESTAMP('2025-12-05 08:10:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-05 09:00:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Routine CBC', (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0002'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Mutesi'), TO_TIMESTAMP('2025-12-06 10:30:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-06 11:00:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Check glucose fasting', (SELECT USER_ID FROM USERS WHERE USERNAME='nsabimana'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0003'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Ndizeye'), TO_TIMESTAMP('2025-12-01 14:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-01 14:30:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Renal panel', (SELECT USER_ID FROM USERS WHERE USERNAME='iradukunda'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0004'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Rurangwa'), TO_TIMESTAMP('2025-12-03 09:15:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-03 09:45:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Liver enzymes', (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0005'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Umutesi'), TO_TIMESTAMP('2025-12-02 13:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-02 13:20:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Cardiac enzymes', (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0006'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Nyiramana'), TO_TIMESTAMP('2025-12-04 07:45:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-04 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'General blood tests', (SELECT USER_ID FROM USERS WHERE USERNAME='nsabimana'));
INSERT INTO ORDERS (PATIENT_ID, PHYSICIAN_ID, ORDERED_AT, COLLECTED_AT, STATUS, NOTES, CREATED_BY) VALUES ((SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0007'), (SELECT PHYSICIAN_ID FROM PHYSICIANS WHERE LAST_NAME='Nshimiyimana'), TO_TIMESTAMP('2025-12-06 15:30:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-12-06 16:00:00','YYYY-MM-DD HH24:MI:SS'), 'PROCESSED', 'Troponin for chest pain', (SELECT USER_ID FROM USERS WHERE USERNAME='iradukunda'));

-- ---------------------------
-- 6) LAB_RESULTS (7) - some normal, some abnormal, some critical
-- ---------------------------
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0001') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='HB'), 14.2, 'g/dL', TO_TIMESTAMP('2025-12-05 09:30:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'), 'Normal', 'Routine check');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0002') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='GLU'), 8.5, 'mmol/L', TO_TIMESTAMP('2025-12-06 11:15:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='nsabimana'), 'Abnormal', 'Fasting level elevated');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0003') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='CR'), 950, 'umol/L', TO_TIMESTAMP('2025-12-01 15:00:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='iradukunda'), 'Critical', 'Markedly elevated creatinine');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0004') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='ALT'), 180, 'U/L', TO_TIMESTAMP('2025-12-03 10:00:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'), 'Abnormal', 'Elevated liver enzyme');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0005') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='TRO'), 5.2, 'ng/mL', TO_TIMESTAMP('2025-12-02 13:30:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='mukamana'), 'Critical', 'Elevated troponin - suspect MI');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0006') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='WBC'), 3.2, '10^9/L', TO_TIMESTAMP('2025-12-04 08:10:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='nsabimana'), 'Abnormal', 'Mild leukopenia');
INSERT INTO LAB_RESULTS (ORDER_ID, TEST_TYPE_ID, RESULT_VALUE, UNITS, RESULT_AT, PROCESSED_BY, INTERPRETATION, COMMENTS) VALUES ((SELECT ORDER_ID FROM ORDERS WHERE PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE MRN='MRN0007') AND ROWNUM=1), (SELECT TEST_TYPE_ID FROM TEST_TYPES WHERE CODE='AST'), 28, 'U/L', TO_TIMESTAMP('2025-12-06 16:15:00','YYYY-MM-DD HH24:MI:SS'), (SELECT USER_ID FROM USERS WHERE USERNAME='iradukunda'), 'Normal', 'Within normal range');

-- ---------------------------
-- 7) ALERTS (7) - create alerts for the critical/abnormal results
-- ---------------------------
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 950 AND ROWNUM=1), 'Critical Creatinine', 'CRITICAL', TO_TIMESTAMP('2025-12-01 15:05:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Creatinine extremely high, notify nephrology', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 5.2 AND ROWNUM=1), 'Critical Troponin', 'CRITICAL', TO_TIMESTAMP('2025-12-02 13:35:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Troponin elevated - possible MI', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 8.5 AND ROWNUM=1), 'High Glucose', 'WARN', TO_TIMESTAMP('2025-12-06 11:20:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Fasting glucose above normal threshold', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 180 AND ROWNUM=1), 'High ALT', 'WARN', TO_TIMESTAMP('2025-12-03 10:05:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Liver enzyme ALT elevated', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 3.2 AND ROWNUM=1), 'Low WBC', 'WARN', TO_TIMESTAMP('2025-12-04 08:15:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Low white blood cell count', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 14.2 AND ROWNUM=1), 'Normal Hemoglobin', 'INFO', TO_TIMESTAMP('2025-12-05 09:40:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'Hemoglobin within normal range', 'Y');
INSERT INTO ALERTS (RESULT_ID, ALERT_TYPE, ALERT_SEVERITY, CREATED_AT, CREATED_BY, DESCRIPTION, IS_ACTIVE) VALUES ((SELECT RESULT_ID FROM LAB_RESULTS WHERE RESULT_VALUE = 28 AND ROWNUM=1), 'Normal AST', 'INFO', TO_TIMESTAMP('2025-12-06 16:20:00','YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', 'AST within normal range', 'Y');

-- ---------------------------
-- 8) ALERT_NOTIFICATIONS (7) - send alerts to physicians (SENT)
-- ---------------------------
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='Critical Creatinine' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='ndizeye'), TO_TIMESTAMP('2025-12-01 15:06:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'IN_APP');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='Critical Troponin' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='kagabo'), TO_TIMESTAMP('2025-12-02 13:36:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'SMS');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='High Glucose' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='mutesi'), TO_TIMESTAMP('2025-12-06 11:25:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'EMAIL');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='High ALT' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='kagabo'), TO_TIMESTAMP('2025-12-03 10:10:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'EMAIL');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='Low WBC' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='mutesi'), TO_TIMESTAMP('2025-12-04 08:20:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'IN_APP');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='Normal Hemoglobin' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='kagabo'), TO_TIMESTAMP('2025-12-05 09:45:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'IN_APP');
INSERT INTO ALERT_NOTIFICATIONS (ALERT_ID, SENT_TO, SENT_AT, STATUS, CHANNEL) VALUES ((SELECT ALERT_ID FROM ALERTS WHERE ALERT_TYPE='Normal AST' AND ROWNUM=1), (SELECT USER_ID FROM USERS WHERE USERNAME='ndizeye'), TO_TIMESTAMP('2025-12-06 16:25:00','YYYY-MM-DD HH24:MI:SS'), 'SENT', 'EMAIL');

-- ---------------------------
-- 9) HOLIDAYS (7) - use December 2025 sample dates
-- ---------------------------
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-25', 'Christmas Day');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-24', 'Christmas Eve');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-31', 'New Year Eve');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2026-01-01', 'New Year Day');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-06', 'Independence (example)');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-09', 'National Remembrance (example)');
INSERT INTO HOLIDAYS (HOLIDAY_DATE, DESCRIPTION) VALUES (DATE '2025-12-20', 'Hospital Annual Day');

-- ---------------------------
-- 10) AUDIT_LOG (7) - sample events
-- ---------------------------
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('INSERT','USERS','mukamana','mukamana', SYSTIMESTAMP, 'Created user mukamana for lab tech');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('INSERT','PATIENTS','MRN0001','mukamana', SYSTIMESTAMP, 'Added patient Jean Hakizimana');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('INSERT','ORDERS','(order for MRN0001)','kagabo', SYSTIMESTAMP, 'Order created for CBC');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('DENIED_ATTEMPT','LAB_RESULTS','(test for MRN0003)','unknown', SYSTIMESTAMP, 'Simulated denied attempt - test policy');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('INFO','ALERTS','Critical Creatinine','SYSTEM', SYSTIMESTAMP, 'Critical alert created for elevated creatinine');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('UPDATE','ALERT_NOTIFICATIONS','(notify to kagabo)','kagabo', SYSTIMESTAMP, 'Physician acknowledged alert (simulated)');
INSERT INTO AUDIT_LOG (EVENT_TYPE, OBJECT_NAME, OBJECT_ID, USER_NAME, EVENT_TIME, DETAILS) VALUES ('INFO','HOLIDAYS','2025-12-25','ingabire', SYSTIMESTAMP, 'Holiday added to calendar');

-- ---------------------------
-- 11) SYSTEM_SETTINGS (7)
-- ---------------------------
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('TAT_HOURS_DEFAULT','24','Default turnaround time in hours', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('ALERT_EMAIL_ENABLED','Y','Enable email notifications for alerts', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('ALERT_SMS_ENABLED','N','Enable SMS notifications for alerts', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('CRITICAL_TAT_HOURS','1','Max hours allowed to respond to critical alerts', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('MAX_ALERT_RETRIES','3','Number of retries for notifications', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('DEFAULT_ALERT_CHANNEL','IN_APP','Default channel to send alerts', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES ('MAINTENANCE_MODE','N','Set to Y to prevent processing during maintenance', (SELECT USER_ID FROM USERS WHERE USERNAME='ingabire'));

-- Final commit
COMMIT;

PROMPT Sample data inserted.
