CREATE TABLE USERS (
  USER_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  USERNAME    VARCHAR2(50) NOT NULL UNIQUE,
  FULL_NAME   VARCHAR2(150) NOT NULL,
  ROLE        VARCHAR2(50) NOT NULL,
  EMAIL       VARCHAR2(150),
  PHONE       VARCHAR2(30),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
  IS_ACTIVE   CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N'))
);



/*----------------------------------------------------------------
  PATIENTS
-----------------------------------------------------------------*/
CREATE TABLE PATIENTS (
  PATIENT_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  MRN         VARCHAR2(20) UNIQUE, -- medical record number
  FIRST_NAME  VARCHAR2(100) NOT NULL,
  LAST_NAME   VARCHAR2(100) NOT NULL,
  DOB         DATE,
  GENDER      CHAR(1) CHECK (GENDER IN ('M','F','O')),
  PHONE       VARCHAR2(20),
  ADDRESS     VARCHAR2(255),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

------------------------------------------
/*----------------------------------------------------------------
  PHYSICIANS
-----------------------------------------------------------------*/
CREATE TABLE PHYSICIANS (
  PHYSICIAN_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  USER_ID      NUMBER UNIQUE, -- optional link to USERS table (if physician has a system account)
  FIRST_NAME   VARCHAR2(100) NOT NULL,
  LAST_NAME    VARCHAR2(100) NOT NULL,
  DEPARTMENT   VARCHAR2(100),
  EMAIL        VARCHAR2(150),
  PHONE        VARCHAR2(30),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_PHYSICIANS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


------------------------------------------
/*----------------------------------------------------------------
  TEST_TYPES: definitions and normal/critical ranges
-----------------------------------------------------------------*/
CREATE TABLE TEST_TYPES (
  TEST_TYPE_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  CODE          VARCHAR2(20) NOT NULL UNIQUE,
  NAME          VARCHAR2(150) NOT NULL,
  UNIT          VARCHAR2(40),
  NORMAL_LOW    NUMBER,
  NORMAL_HIGH   NUMBER,
  CRITICAL_LOW  NUMBER,
  CRITICAL_HIGH NUMBER,
  SAMPLE_TYPE   VARCHAR2(50), -- e.g., 'Blood','Urine'
  CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

------------------------------------------
/*----------------------------------------------------------------
  ORDERS: lab orders (not using reserved WORD "ORDER")
-----------------------------------------------------------------*/
CREATE TABLE ORDERS (
  ORDER_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  PATIENT_ID    NUMBER NOT NULL,
  PHYSICIAN_ID  NUMBER,
  ORDERED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  COLLECTED_AT  TIMESTAMP,
  STATUS        VARCHAR2(30) DEFAULT 'PENDING', -- PENDING, COLLECTED, PROCESSED, CANCELLED
  NOTES         VARCHAR2(1000),
  CREATED_BY    NUMBER, -- user who created the order
  CONSTRAINT FK_ORDERS_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
  CONSTRAINT FK_ORDERS_PHYSICIAN FOREIGN KEY (PHYSICIAN_ID) REFERENCES PHYSICIANS(PHYSICIAN_ID),
  CONSTRAINT FK_ORDERS_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);


------------------------------------------
/*----------------------------------------------------------------
  LAB_RESULTS: actual test results
-----------------------------------------------------------------*/
CREATE TABLE LAB_RESULTS (
  RESULT_ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ORDER_ID         NUMBER NOT NULL,
  TEST_TYPE_ID     NUMBER NOT NULL,
  RESULT_VALUE     NUMBER,
  UNITS            VARCHAR2(40),
  RESULT_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROCESSED_BY     NUMBER, -- USERS.USER_ID
  INTERPRETATION   VARCHAR2(100), -- Normal, Abnormal, Critical, Unknown
  COMMENTS         VARCHAR2(2000),
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_RESULTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RESULTS_TESTTYPE FOREIGN KEY (TEST_TYPE_ID) REFERENCES TEST_TYPES(TEST_TYPE_ID),
  CONSTRAINT FK_RESULTS_PROCESSEDBY FOREIGN KEY (PROCESSED_BY) REFERENCES USERS(USER_ID)
);


------------------------------------------
/*----------------------------------------------------------------
  ALERTS: generated alerts for abnormal/critical results
-----------------------------------------------------------------*/
CREATE TABLE ALERTS (
  ALERT_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  RESULT_ID      NUMBER NOT NULL,
  ALERT_TYPE     VARCHAR2(100), -- e.g., 'Critical value','Abnormal trend'
  ALERT_SEVERITY VARCHAR2(20) DEFAULT 'INFO' CHECK (ALERT_SEVERITY IN ('INFO','WARN','CRITICAL')),
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY     VARCHAR2(50) DEFAULT 'SYSTEM', -- 'SYSTEM' or username
  DESCRIPTION    VARCHAR2(2000),
  IS_ACTIVE      CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT FK_ALERTS_RESULT FOREIGN KEY (RESULT_ID) REFERENCES LAB_RESULTS(RESULT_ID) ON DELETE CASCADE
);


------------------------------------------
/*----------------------------------------------------------------
  ALERT_NOTIFICATIONS: notifications sent to users for alerts
-----------------------------------------------------------------*/
CREATE TABLE ALERT_NOTIFICATIONS (
  NOTIF_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ALERT_ID         NUMBER NOT NULL,
  SENT_TO          NUMBER NOT NULL, -- USERS.USER_ID
  SENT_AT          TIMESTAMP DEFAULT SYSTIMESTAMP,
  DELIVERED_AT     TIMESTAMP,
  ACKNOWLEDGED_BY  NUMBER,
  ACKNOWLEDGED_AT  TIMESTAMP,
  STATUS           VARCHAR2(20) DEFAULT 'SENT', -- SENT, DELIVERED, ACKNOWLEDGED, FAILED
  CHANNEL          VARCHAR2(50), -- EMAIL, SMS, IN_APP
  CONSTRAINT FK_NOTIF_ALERT FOREIGN KEY (ALERT_ID) REFERENCES ALERTS(ALERT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_NOTIF_SENTTO FOREIGN KEY (SENT_TO) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_NOTIF_ACKBY FOREIGN KEY (ACKNOWLEDGED_BY) REFERENCES USERS(USER_ID)
);


------------------------------------------
/*----------------------------------------------------------------
  HOLIDAYS: used to block weekday/holiday DML according to project rule
-----------------------------------------------------------------*/
CREATE TABLE HOLIDAYS (
  HOLIDAY_DATE DATE PRIMARY KEY,
  DESCRIPTION  VARCHAR2(255),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
);

------------------------------------------
/*----------------------------------------------------------------
  AUDIT_LOG: logs all DML attempts, denials, and relevant events
-----------------------------------------------------------------*/
CREATE TABLE AUDIT_LOG (
  AUDIT_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  EVENT_TYPE   VARCHAR2(30) NOT NULL, -- INSERT, UPDATE, DELETE, DENIED_ATTEMPT, INFO
  OBJECT_NAME  VARCHAR2(100),
  OBJECT_ID    VARCHAR2(100),
  USER_NAME    VARCHAR2(100),
  EVENT_TIME   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  DETAILS      VARCHAR2(4000)
);


/*----------------------------------------------------------------
  SYSTEM_SETTINGS: configuration table (e.g., TAT thresholds, feature flags)
-----------------------------------------------------------------*/
CREATE TABLE SYSTEM_SETTINGS (
  SETTING_KEY   VARCHAR2(100) PRIMARY KEY,
  SETTING_VALUE VARCHAR2(4000),
  DESCRIPTION   VARCHAR2(1000),
  UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_BY    NUMBER REFERENCES USERS(USER_ID)
);